language: node_js
node_js: node
os:
- linux
- osx
dist: trusty
sudo: true
git:
  depth: 3
addons:
  apt:
    packages:
env:
  - secure: J1hH4ZB7Cu9jkli6LGVcyS5RB/YMFxgYspnWZ2EXM1jJJjBf5NtI79wkd1ubGRy7w/KY1ugQS92hHYupjtA7dISp8wX0kqsYXcHBAWO753W9txFP9V9GuInjFOEXmx+ejUj+x27vbNLcocB83/iAdUs8BKQdc0ARJF6vPjhKy3Sc9Lf9knqSlUZV8eINu4MTOHZNqQsVtOdDPymu2nW2ET+2B/4cnNHnalVdTnhXEqvCNZv621MGNu5CUsUQw4Kl82idmo9gFA9TWFUdiXY3ajT3HIj8CQBhr301+5DQ9RMeTRtT7vge6Ezqbc+75cdYSJUAL2uu/6VdSXDrb9G4uDFKGLiqSHcdjGUgGNLuEqrgkb2WeHlvjMMfmgbhw7u/HcFdej1bVoJp5XTiai1BOG4n0Fm9xZLMUFb4TOfCdsunkO8aH45h94v7DzzUIlbkSjCTLPdVI7RX0fUVpQ65xY26LNdh/DW6d7S4Bjuq7ZBOAf5Ku14Dwa65SBvEtX8NWVKgQ8Ll9L3Xi76HxJwLnCwTmNHKrbALDxCKvRn3JdUxe/SMJLIA8/RXblxqglBkqlVdslYnFxN9Tr6A6XYJgy9yzC3bo/8DsXxG9KzJkEfglgxS4v6UIaErKcttk+CdfOYU3AcWGjpN7sPLHeiaXZu8mNWiqqiEsSBvP2ys/JU=
  - secure: fn4ZUumT5KPIgtoPhb6EUmzQs8vEut3N4iiPqxvex1Ytjzvb81CcNOOKK0kW4xvsC0UuwO8eAhPdKNE/2h23Qil/+nb8ebUVEJgfa3M2gfz7JRwu9Xem7iAmmjQ8Ptps9dQc95QXO/chnUYuSpAAArqa4fIGrCqreDLpNfPgNeYo3//YCHTIAZWgK0scAPTm8AR8d8Vgir/3mIF0/uayhUccjtOl0ZU382Of1lUiOuusB12PPLD82rsdvTz/o1M2pB10+mOG96A7q8mfZ8RszGsQn7gKD3vs4wn7b0a8VbrWX/xva8mD3bh8i0X77wuqgyWMgpyvaQwockQ0P7vTS6tVA3zDCKERrgvUdIUiHXOqcHhf0dG/JkMjwyUSjn/Ec/8Ty/fKG2+U5J1aZblR3p0pDLTpZkbYDIAiJkD29grW0OqAU65uOVa0N9qTqJVGyJwg6u+WEeBYxI4z5kluo4qMr9+BsJKzwbpn9RQ+d1IotcChC4/xdFLMMKIAwqcqEFAm9aYFBVZhVLipH0QxVCujwNlkkdwurIuiT2T6Ug1jFUn879hG7GEQcVGkXWlotemZQrkZgDXX+n/qrcmUNFd0GuZWPCL0/wrbIn6NI1/Ry7zJAoZsIqWzh/5iEuZXpxS7R4GRnGzfiu+SxSD+W2sofMh9JFC1YvRY4hfHuus=
install:
- npm install
before_script:
- chmod +x build/package.sh
- chmod +x build/createConf.sh
script:
- build/createConf.sh
- npm run build
- build/package.sh
notifications:
  email:
    on_success: never
deploy:
  provider: releases
  api_key:
    secure: XtsXAeKYmA+gQ8x5z11Gp4GOBBf6E3+7a085JmukHDbH1h3izmbgvJx/pNYmsq6srn4165+T51tCWbH25PE2BtScrMq7TuZhtbvtqY8S7TXRZWYk1FoAPKytsfB4OHr71TnpwrdbJAJJsXWO5xeGyMZLJbgwpIsOVhACFmnQyd7OApZ4w8IPVpiodt7TkvS38oiHjImEsagSLQIVdueYOnOzgAU4kcrHWxRXNY37i3HPAUF3og5XZsRbchGf/PjDwNkb7ozitA1aQgD64omsODbU1vyj05F+cWBE6QOZfpZ8vhWfo2sKo7DtJcNd1NZg3xpFxyxTHICj3JKDps5JBS4BwPdBw3tznesIkWJU8ULtWW0nrEFCezsuvPs1/SucipUGx1nf4Pl1g/8sOBUnX93h9CHSNeRm5x7lpsE6PgQWi84ANA3g2S3buRUSoSX+qa/gWq1TwMsAKbEvjfwCyrTUYzQg3gvDAarFhNuJhBIK/21wWhhtP/CcFiVHw600zQHbrEv9et3pUAuKDCymxYqJJW39fRHQZcwBKl18HljCNrH1UtNvJH2DnrkweDdgeHNOXFiIUPc4ytzUSm2uBDDDxIX/EEFvtGN27Ue6Vggo0RzXbneJsVTDmLwZnXDE5xncHKjswpPfMoPxU3ShLBcKd6SWRlTG1QfWHBWqWt0=
  file:
    - release-builds/electron-live2d-linux-x64.tar.gz
    - release-builds/electron-live2d-darwin-x64.tar.gz
  skip_cleanup: true
  on:
    tags: true
