language: node_js
node_js: node
os:
- linux
- osx
dist: trusty
sudo: true
git:
  depth: 3
addons:
  apt:
    packages:
cache:
  directories:
  - node_modules
install:
- npm install

before_script:
- chmod +x build/package.sh

script:
- npm run build
- build/package.sh

notifications:
  email:
    on_success: never

deploy:
  provider: releases
  api_key: a532207747af7e9e7465c0871e7caad980e8b667
  file: 
    - release-builds/electron-live2d-linux-x64.tar.gz
    - release-builds/electron-live2d-drawin-x64.tar.gz
  skip_cleanup: true
  on:
    tags: true