environment:
  nodejs_version: "7"

platform: 
  - x64
clone_depth: 3

cache: 
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

before_build:
  - ps: build\createConf.ps1

build_script:
  - npm run build

after_build:
  - npm run package-win32-x64
  - ps: build\package.ps1
