environment:
  nodejs_version: "7"
  XUNFEI_APP_ID:
    secure: 0yuuz2CEPL+tXdU5UTlLTw==
  XUNFEI_APP_KEY:
    secure: MJX5AWtT57sMgTOVAPvCH4w9qQ4tsubSIb01stadk7g=
  FACEPP_KEY:
    secure: 3rd662BZdj8RVHFpg9aCOezzev3uYg97KBPZucNsvHDJuuqO3kMHYAQq4ZrkIv5Z
  FACEPP_SECRET:
    secure: D0d8kHC5hCtMbzn2JAG9xX2G9/zTS+ica7UB9cGwwQF91RZWwm/yXs2JYzg2je1W
  YYY_KEY:
    secure: JOb4IN61SFeGz0b9IsyjsW25djfTvEeGPyiTGXakDiTtnzMFEE6Ja6fJL6+FpZjx
platform: 
  - x64
clone_depth: 3

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

before_build:
  - ps: build\checkEnv.ps1
  - ps: build\createConf.ps1

build_script:
  - npm run build

after_build:
  - npm run package-win32-x64
  - ps: build\package.ps1

artifacts:
  - path: release-builds/electron-live2d-win32-x64.zip
    name: electron-live2d-win-x64

deploy:
  provider: GitHub
  auth_token:
    secure: 2bhzwda2nhlr7agSQL96Lu81Hsmxdod21jyXjEXX36DYM1d8L8bIW5hNGb5hOCL0
  draft: false
  artifact: electron-live2d-win-x64
  prerelease: false
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true